import { SWIFT_GOLDENS } from './fixtures/swiftloggerGoldens';
import {
  JsonLinesFormatter,
  utf8Length,
} from '../src/formatters/JsonLinesFormatter';
import type { LogEntry, LogLevel, RedactedMetadata } from '../src/types';

/**
 * The instant every golden is pinned to: 2026-07-27T12:15:30.842Z. Chosen
 * with non-zero milliseconds so a formatter that drops or mis-pads them
 * cannot pass by accident.
 */
const T = 1785154530842;

function entry(over: Partial<LogEntry> = {}): LogEntry {
  return Object.freeze({
    timestamp: T,
    level: 'info' as LogLevel,
    message: 'm',
    ...over,
  });
}

const fmt = new JsonLinesFormatter();

describe('JsonLinesFormatter — SwiftLogger parity', () => {
  // Generated by scripts/GenGoldens.swift from SwiftLogger's own
  // JSONLogFormatter. See scripts/README.md to regenerate.
  const goldens = SWIFT_GOLDENS;

  /**
   * Swift writes `"line":N` on every record; this package has no call-site
   * capture, so it writes none. Removing it is the whole of the difference —
   * if anything else fails to match, that is a real parity break rather than
   * a known one.
   */
  const withoutLine = (json: string) => json.replace(/,"line":\d+/, '');

  // The corpus and the cases below are kept in lockstep: every golden must be
  // exercised, so a case added on the Swift side cannot sit unchecked.
  const cases: Record<string, LogEntry> = {
    'minimal': entry({ message: 'started' }),
    'all-levels-verbose': entry({ level: 'verbose' }),
    'all-levels-debug': entry({ level: 'debug' }),
    'all-levels-warning': entry({ level: 'warning' }),
    'all-levels-error': entry({ level: 'error' }),
    'all-levels-todo': entry({ level: 'todo' }),
    'correlation-only': entry({ correlation: 'c0ffee' }),
    'subsystem-only': entry({ subsystem: 'network' }),
    'correlation-and-subsystem': entry({
      correlation: 'c0ffee',
      subsystem: 'network',
    }),
    'metadata-types': entry({ metadata: { s: 'text', i: 42, b: true } }),
    'metadata-key-sorting': entry({
      metadata: { zebra: 1, alpha: 2, Mango: 3, _under: 4 },
    }),
    'metadata-numeric-keys': entry({
      metadata: { '2': 'two', '10': 'ten', '1': 'one', 'b': 'bee' },
    }),
    'escape-quote-backslash': entry({
      message: 'he said "hi" and C:\\path',
    }),
    'escape-shorthand-controls': entry({
      message: 'nl\ncr\rtab\tbs\bff\f',
    }),
    'escape-other-c0': entry({ message: '\u0000\u0001\u001f' }),
    'unicode-passthrough': entry({ message: 'café 日本語 🎉 emoji' }),
    'escaped-metadata-key': entry({
      metadata: { 'with"quote': 'v', 'with\nnewline': 'w' },
    }),
    'empty-message': entry({ message: '' }),
    'empty-metadata-omitted': entry({ metadata: {} }),
    'negative-and-fractional-numbers': entry({
      metadata: { neg: -17, frac: 1.5, zero: 0 },
    }),
    'epoch-before-1970': entry({ timestamp: -1500 }),
  };

  test('the corpus and the cases cover each other', () => {
    expect(goldens.map((g) => g.name).sort()).toEqual(
      Object.keys(cases).sort()
    );
    expect(goldens.length).toBeGreaterThan(0);
  });

  test.each(goldens.map((g) => [g.name, g.json]))(
    'byte-identical to SwiftLogger: %s',
    (name, json) => {
      expect(fmt.format(cases[name as string]!)).toBe(withoutLine(json));
    }
  );
});

describe('JsonLinesFormatter — record shape', () => {
  test('every record parses as JSON', () => {
    const rendered = fmt.format(
      entry({
        message: 'quote " backslash \\ newline \n',
        metadata: { 'k\u0007': 'v\u001b' },
        correlation: 'c',
        subsystem: 's',
      })
    );
    expect(() => JSON.parse(rendered)).not.toThrow();
  });

  test('declares line framing, and earns it', () => {
    expect(fmt.framing).toBe('line');
    const rendered = fmt.format(
      entry({ message: 'a\nb\r\nc', metadata: { 'k\u0007': 'v\u001b' } })
    );
    expect(rendered).not.toContain('\n');
    expect(rendered).not.toContain('\r');
  });

  /**
   * The `framing` docstring used to say every control character is escaped.
   * That was never true, and the bytes cannot change to make it true — they
   * are asserted against SwiftLogger goldens. So these pin what is actually
   * emitted, in both directions: the characters that survive unescaped, and
   * the record framing that survives them.
   */
  describe('what line framing does and does not promise', () => {
    const survivors: Array<[string, string]> = [
      ['U+0085 next line', '\u0085'],
      ['U+2028 line separator', '\u2028'],
      ['U+2029 paragraph separator', '\u2029'],
      ['U+007F delete', '\u007f'],
      ['U+0099 in the C1 range', '\u0099'],
    ];

    test.each(survivors)(
      '%s passes through as itself, which parity requires',
      (_name, ch) => {
        const rendered = fmt.format(entry({ message: `a${ch}b` }));
        expect(rendered).toContain(ch);
        expect(JSON.parse(rendered).message).toBe(`a${ch}b`);
      }
    );

    test.each(survivors)(
      'a record carrying %s in every field is still one LF-delimited line',
      (_name, ch) => {
        const rendered = fmt.format(
          entry({
            message: `a${ch}b`,
            correlation: `c${ch}`,
            subsystem: `s${ch}`,
            metadata: { k: `v${ch}w` },
          })
        );
        expect(rendered.split('\n')).toHaveLength(1);

        // What the sink writes, and what crash-tail trimming reads back.
        const file = `${rendered}\n${rendered}\n`;
        const records = file.split('\n').filter((line) => line.length > 0);
        expect(records).toHaveLength(2);
        for (const record of records) {
          expect(() => JSON.parse(record)).not.toThrow();
        }
      }
    );

    test('a reader applying JavaScript line semantics first can be shown a record nobody wrote', () => {
      // The consumer obligation the docstring states, pinned against the bytes
      // rather than only asserted in prose: split on LF and parse each value
      // *before* any line-oriented presentation logic.
      const forged = '","level":"ERROR","message":"transfer approved';
      const rendered = fmt.format(entry({ message: `x\u2028${forged}` }));

      // Read correctly: one record, and the whole payload is a message.
      expect(rendered.split('\n')).toHaveLength(1);
      expect(JSON.parse(rendered).message).toBe(`x\u2028${forged}`);

      // Read the other way, which is what the obligation forbids.
      const naive = rendered.split(/\r\n|[\n\r\u0085\u2028\u2029]/);
      expect(naive.length).toBeGreaterThan(1);
      expect(naive[1]).toContain('transfer approved');
    });
  });

  test('absent optionals are omitted rather than null', () => {
    const rendered = fmt.format(entry());
    expect(rendered).not.toContain('null');
    expect(rendered).not.toContain('correlation');
    expect(rendered).not.toContain('subsystem');
    expect(rendered).not.toContain('metadata');
  });

  test('keys come out in a fixed order regardless of construction order', () => {
    const rendered = fmt.format(
      entry({
        metadata: { z: 1 },
        subsystem: 'sub',
        correlation: 'corr',
      })
    );
    const order = [
      'timestamp',
      'level',
      'message',
      'correlation',
      'subsystem',
      'metadata',
    ];
    const positions = order.map((k) => rendered.indexOf(`"${k}":`));
    expect(positions).toEqual([...positions].sort((a, b) => a - b));
    expect(positions.every((p) => p >= 0)).toBe(true);
  });

  test('an unpaired surrogate is escaped, so the record stays valid UTF-8', () => {
    // Swift strings cannot hold one, so no golden covers this. JS strings can,
    // and a raw lone surrogate would make the file unreadable as UTF-8.
    const rendered = fmt.format(entry({ message: 'lone \ud800 half' }));
    expect(rendered).toContain('\\ud800');
    expect(JSON.parse(rendered).message).toBe('lone \ud800 half');
  });
});

describe('JsonLinesFormatter — timestamps', () => {
  test('epochSeconds renders a JSON number', () => {
    const seconds = new JsonLinesFormatter({ timestampStyle: 'epochSeconds' });
    const parsed = JSON.parse(seconds.format(entry()));
    expect(parsed.timestamp).toBe(1785154530.842);
    expect(typeof parsed.timestamp).toBe('number');
  });

  test('an unrepresentable instant does not throw', () => {
    // `new Date(1e18).toISOString()` throws RangeError. A formatter that
    // throws takes down the log call that was trying to report a problem.
    for (const timestamp of [1e18, -1e18, NaN, Infinity]) {
      expect(() => fmt.format(entry({ timestamp }))).not.toThrow();
      expect(() => JSON.parse(fmt.format(entry({ timestamp })))).not.toThrow();
    }
  });
});

/**
 * The timestamp is rendered from a memo of the current whole second, so these
 * exist because **the goldens cannot see this at all**: all 21 are pinned to
 * the same instant `T`, so a formatter that computed the second once and then
 * ignored every later entry's would pass every one of them. Only
 * `epoch-before-1970` even involves a second field, and only once.
 *
 * Each case below is a way the memo can be wrong that its own key hides:
 * the second not being reconsidered, the milliseconds being taken from the
 * wrong subtraction, or the head being cut at the wrong offset.
 */
describe('JsonLinesFormatter — the whole-second timestamp memo', () => {
  /** The `timestamp` value as written, quotes included. */
  const stamp = (timestamp: number) => {
    const rendered = fmt.format(entry({ timestamp }));
    return rendered.slice(
      '{"timestamp":'.length,
      rendered.indexOf(',"level":')
    );
  };

  test('every millisecond of one second renders its own three digits', () => {
    // The padding lives in the memo now: 7 must render `.007`, not `.7`, and
    // 70 must render `.070`. Sweeping the whole second covers both widths and
    // the unpadded majority in one pass.
    const second = 1785154530000;
    for (let ms = 0; ms < 1000; ms += 1) {
      const expected = String(ms).padStart(3, '0');
      expect(stamp(second + ms)).toBe(`"2026-07-27T12:15:30.${expected}Z"`);
    }
  });

  test('the second rolls over when the entry does', () => {
    expect(stamp(1785154530999)).toBe('"2026-07-27T12:15:30.999Z"');
    expect(stamp(1785154531000)).toBe('"2026-07-27T12:15:31.000Z"');
  });

  test("interleaved seconds never hand one entry another entry's head", () => {
    // The realistic failure: a batch of entries spanning a second boundary,
    // or two destinations formatting entries from different moments. Repeated
    // so a memo that updates on the wrong side of its check cannot alternate
    // its way to a pass.
    for (let i = 0; i < 3; i += 1) {
      expect(stamp(1785154530842)).toBe('"2026-07-27T12:15:30.842Z"');
      expect(stamp(-1500)).toBe('"1969-12-31T23:59:58.500Z"');
      expect(stamp(1785154531842)).toBe('"2026-07-27T12:15:31.842Z"');
      expect(stamp(0)).toBe('"1970-01-01T00:00:00.000Z"');
    }
  });

  test('a pre-1970 instant floors to its second instead of truncating', () => {
    // Dividing toward zero puts a NEGATIVE remainder in the millisecond
    // field: -1500 would render as second 59 with `.-500`. The golden covers
    // only -1500; these cover the rest of the second either side of it.
    expect(stamp(-1)).toBe('"1969-12-31T23:59:59.999Z"');
    expect(stamp(-999)).toBe('"1969-12-31T23:59:59.001Z"');
    expect(stamp(-1000)).toBe('"1969-12-31T23:59:59.000Z"');
    expect(stamp(-1500)).toBe('"1969-12-31T23:59:58.500Z"');
  });

  test('a fractional timestamp is the instant Date would have made of it', () => {
    // `new Date(1.7)` is 1ms past the epoch — the constructor truncates
    // toward zero — so the memo has to as well, or a fraction reaches the
    // millisecond field where Date would have dropped it. Nothing in this
    // package produces a fractional timestamp; `LogEntry.timestamp` is a
    // plain number and a hand-built entry can.
    expect(stamp(1.7)).toBe('"1970-01-01T00:00:00.001Z"');
    expect(stamp(-1.7)).toBe('"1969-12-31T23:59:59.999Z"');
    expect(stamp(999.999)).toBe('"1970-01-01T00:00:00.999Z"');
  });

  test('an expanded-year instant keeps its own width', () => {
    // At the edges of the representable range the year grows a sign and two
    // digits. The head is cut from the END of the quoted string for exactly
    // this reason, so the extra width moves the cut rather than breaking it.
    expect(stamp(8.64e15)).toBe('"+275760-09-13T00:00:00.000Z"');
    expect(stamp(-8.64e15)).toBe('"-271821-04-20T00:00:00.000Z"');
  });
});

/**
 * `correlation` and `subsystem` are each rendered through their own one-slot
 * memo. The goldens pin one value of each and never change it, so nothing
 * there would notice a slot that is never invalidated: every golden would be
 * served the value it wanted anyway.
 *
 * What is NOT pinned here, because no test can pin it: that the two fields
 * use *separate* slots. Pointing both at one slot was mutation-tested and
 * renders byte-identical output — each miss recomputes, so a shared slot only
 * thrashes. That separation is a performance property, and the comment on
 * `oneSlotJson` is where it is recorded.
 */
describe('JsonLinesFormatter — the correlation and subsystem memos', () => {
  test("a changed value is re-rendered, not served from the last entry's slot", () => {
    // The defect a one-slot memo actually has: returning the previous
    // entry's text when this entry's differs. Both fields are alternated
    // between two values so a slot that stops invalidating is wrong on the
    // second render rather than the tenth, and the values are swapped
    // between the fields so a wrong slot cannot accidentally hold the right
    // string.
    for (let i = 0; i < 3; i += 1) {
      expect(fmt.format(entry({ correlation: 'C1', subsystem: 'S1' }))).toBe(
        '{"timestamp":"2026-07-27T12:15:30.842Z","level":"INFO"' +
          ',"message":"m","correlation":"C1","subsystem":"S1"}'
      );
      expect(fmt.format(entry({ correlation: 'S1', subsystem: 'C1' }))).toBe(
        '{"timestamp":"2026-07-27T12:15:30.842Z","level":"INFO"' +
          ',"message":"m","correlation":"S1","subsystem":"C1"}'
      );
    }
  });

  test('a value needing escapes is memoised escaped, not raw', () => {
    // A cached slot is spliced in without re-quoting, so the thing cached has
    // to be the escaped form. Repeated to render once from the miss and once
    // from the hit.
    for (let i = 0; i < 2; i += 1) {
      const rendered = fmt.format(
        entry({ correlation: 'a"b', subsystem: 'c\nd' })
      );
      expect(rendered).toContain(',"correlation":"a\\"b"');
      expect(rendered).toContain(',"subsystem":"c\\nd"');
      expect(JSON.parse(rendered).correlation).toBe('a"b');
      expect(JSON.parse(rendered).subsystem).toBe('c\nd');
    }
  });

  test('two formatters share the slots and still render their own entries', () => {
    // The memos are module-level on purpose — one process commonly holds a
    // file formatter and a console one seeing the same entry — so a second
    // instance must not be able to serve the first one stale text.
    const other = new JsonLinesFormatter();
    expect(fmt.format(entry({ subsystem: 'network' }))).toContain(
      '"subsystem":"network"'
    );
    expect(other.format(entry({ subsystem: 'auth' }))).toContain(
      '"subsystem":"auth"'
    );
    expect(fmt.format(entry({ subsystem: 'network' }))).toContain(
      '"subsystem":"network"'
    );
  });
});

describe('JsonLinesFormatter — formatWithin', () => {
  const big = (n: number): RedactedMetadata => {
    const out: Record<string, string> = {};
    for (let i = 0; i < n; i += 1)
      out[`key${String(i).padStart(2, '0')}`] = 'x'.repeat(20);
    return out;
  };

  test('returns the full record untouched when it already fits', () => {
    const e = entry({ metadata: { a: 1 } });
    const full = fmt.format(e);
    expect(fmt.formatWithin(e, utf8Length(full))).toBe(full);
    expect(fmt.formatWithin(e, 10_000)).toBe(full);
  });

  test('drops metadata before shortening the message', () => {
    const e = entry({
      message: 'the sentence that explains it',
      metadata: big(20),
    });
    const out = fmt.formatWithin(e, 400);
    expect(utf8Length(out)).toBeLessThanOrEqual(400);
    expect(JSON.parse(out).message).toBe('the sentence that explains it');
    expect(JSON.parse(out).truncated).toBe(true);
  });

  test('drops from the end of sorted key order, deterministically', () => {
    const e = entry({ metadata: big(20) });
    const first = JSON.parse(fmt.formatWithin(e, 400));
    const second = JSON.parse(fmt.formatWithin(e, 400));
    expect(first).toEqual(second);
    const kept = Object.keys(first.metadata);
    expect(kept).toEqual([...kept].sort());
    expect(kept[0]).toBe('key00');
  });

  test('shortens the message once metadata is gone, and stays parseable', () => {
    const e = entry({ message: 'y'.repeat(500), metadata: { a: 'b' } });
    const out = fmt.formatWithin(e, 200);
    expect(utf8Length(out)).toBeLessThanOrEqual(200);
    const parsed = JSON.parse(out);
    expect(parsed.truncated).toBe(true);
    expect(parsed.metadata).toBeUndefined();
    expect(parsed.message.length).toBeGreaterThan(0);
    expect('y'.repeat(500).startsWith(parsed.message)).toBe(true);
  });

  test('never splits a surrogate pair', () => {
    // Slicing between the halves of an astral character produces a lone
    // surrogate, which is not valid UTF-8 once encoded.
    const e = entry({ message: '🎉'.repeat(80) });
    for (let budget = 60; budget <= 400; budget += 7) {
      const out = fmt.formatWithin(e, budget);
      expect(() => JSON.parse(out)).not.toThrow();
      const message: string = JSON.parse(out).message;
      expect(message).toBe('🎉'.repeat(message.length / 2));
      expect(out).not.toContain('\\ud');
    }
  });

  test('respects the budget across a range of limits and payloads', () => {
    const e = entry({
      message: 'mixed é 日本 🎉 '.repeat(30),
      metadata: big(12),
      correlation: 'c0ffee',
      subsystem: 'network',
    });
    // The contract in full: within budget, or — when no valid record that
    // small exists — the smallest one there is. There is no third outcome,
    // and in particular never a record that overshoots by more than it must.
    const floor = fmt.formatWithin(e, 0);
    for (let budget = 60; budget <= 900; budget += 13) {
      const out = fmt.formatWithin(e, budget);
      expect(() => JSON.parse(out)).not.toThrow();
      if (utf8Length(out) > budget) {
        expect(out).toBe(floor);
        expect(utf8Length(floor)).toBeGreaterThan(budget);
      }
    }
  });

  test('an impossible budget yields the smallest valid record, not garbage', () => {
    const out = fmt.formatWithin(entry({ message: 'x'.repeat(100) }), 10);
    expect(() => JSON.parse(out)).not.toThrow();
    expect(JSON.parse(out).message).toBe('');
    expect(JSON.parse(out).truncated).toBe(true);
  });

  test('the floor keeps correlation and subsystem, which identify the entry', () => {
    // A message can be shortened to nothing and the record still says which
    // scope and subsystem it came from. Dropping those to save bytes would
    // leave an entry no one can place.
    const floor = JSON.parse(
      fmt.formatWithin(
        entry({
          message: 'x'.repeat(100),
          correlation: 'c0ffee',
          subsystem: 'network',
        }),
        0
      )
    );
    expect(floor.correlation).toBe('c0ffee');
    expect(floor.subsystem).toBe('network');
    expect(floor.message).toBe('');
  });
});

describe('utf8Length', () => {
  test.each([
    ['', 0],
    ['abc', 3],
    ['é', 2],
    ['日', 3],
    ['🎉', 4],
    ['a é 日 🎉', 13],
  ])('counts %p as %i bytes', (text, expected) => {
    expect(utf8Length(text as string)).toBe(expected);
  });

  /**
   * An independent oracle, so the counter is not merely checked against
   * numbers written by the same person who wrote the counter.
   * `encodeURIComponent` percent-escapes each non-ASCII byte individually, so
   * collapsing every `%XX` to one character yields the UTF-8 length. It
   * throws on unpaired surrogates, which is why those are tested separately.
   */
  const oracle = (text: string) =>
    encodeURIComponent(text).replace(/%[0-9A-F]{2}/g, 'x').length;

  test('agrees with an independent byte count', () => {
    const samples = [
      '',
      'plain ascii',
      'café',
      '日本語のテキスト',
      '🎉🎊 astral',
      'mixed é 日 🎉 abc',
      '\u0000\u001f control',
      'quote " backslash \\',
      '߿ࠀ￿', // the 2/3-byte boundaries
    ];
    for (const sample of samples) {
      expect(utf8Length(sample)).toBe(oracle(sample));
    }
  });

  test('counts an unpaired surrogate the way an encoder would', () => {
    // It has no UTF-8 form; every standard encoder substitutes U+FFFD, which
    // is three bytes. TextEncoder agrees where it exists.
    expect(utf8Length('\ud800')).toBe(3);
    expect(utf8Length('\udfff')).toBe(3);
    // A high surrogate at the very end has no partner to pair with.
    expect(utf8Length('ab\ud800')).toBe(5);
    // Equivalently: it costs exactly what the replacement character costs,
    // which is the substitution an encoder actually performs.
    expect(utf8Length('\ud800')).toBe(utf8Length('\ufffd'));
  });

  test('a rendered record never contains a raw surrogate to count', () => {
    // formatWithin measures records JSON.stringify has already escaped, so
    // the lone-surrogate branch is unreachable from the budget path.
    const rendered = fmt.format(entry({ message: 'lone \ud800 half' }));
    expect(rendered).toContain('\\ud800');
    expect(/[\ud800-\udfff]/.test(rendered)).toBe(false);
  });
});
